# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-10 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
