# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-10 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0002_auto_20170509_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='myactivities',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
