# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0004_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
